using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RIAPP.DataService.DomainService.Exceptions;
using RIAPP.DataService.DomainService.Interfaces;
using RIAPP.DataService.DomainService.Types;
using RIAPP.DataService.Resources;
using RIAPP.DataService.Utils;
using RIAPP.DataService.Utils.Extensions;

namespace RIAPP.DataService.DomainService
{
    public class ServiceOperationsHelper : IDisposable, IServiceOperationsHelper
    {
        /// <summary>
        ///     Already created instances of DataManagers indexed by modelType
        /// </summary>
        private readonly ConcurrentDictionary<Type, object> _dataManagers;

        private BaseDomainService _domainService;

        public ServiceOperationsHelper(BaseDomainService domainService)
        {
            _domainService = domainService;
            _dataManagers = new ConcurrentDictionary<Type, object>();
        }

        private IServiceContainer _services
        {
            get { return _domainService.ServiceContainer; }
        }

        public void Dispose()
        {
            _domainService = null;
            var dataManagers = _dataManagers.Values.Where(m => m is IDisposable).Select(m => (IDisposable) m).ToArray();
            Array.ForEach(dataManagers, m => { m.Dispose(); });
            _dataManagers.Clear();
        }

        public object GetMethodOwner(MethodInfoData methodData)
        {
            if (!methodData.isInDataManager)
                return _domainService;
            if (methodData.entityType == null)
                return _domainService;
            var metadata = MetadataHelper.GetInitializedMetadata(_domainService);
            var managerInstance = _dataManagers.GetOrAdd(methodData.entityType,
                t => { return metadata.DataManagerContainer.GetDataManager(_domainService, t); });
            return managerInstance;
        }

        public async Task AfterExecuteChangeSet()
        {
            var dataManagers = _dataManagers.Values.Select(m => (IDataManager) m);
            foreach (var dataManager in dataManagers)
                await dataManager.AfterExecuteChangeSet().ConfigureAwait(false);
        }

        public void ApplyValues(object entity, RowInfo rowInfo, string path, ValueChange[] values, bool isOriginal)
        {
            var dbSetInfo = rowInfo.dbSetInfo;
            var dataHelper = _services.DataHelper;
            Array.ForEach(values, val =>
            {
                var fullName = path + val.fieldName;
                var fieldInfo = dataHelper.getFieldInfo(dbSetInfo, fullName);
                if (!fieldInfo.GetIsIncludeInResult())
                    return;
                //Server Side calculated fields are never set on entities from updates
                if (fieldInfo.fieldType == FieldType.ServerCalculated)
                    return;

                if (fieldInfo.fieldType == FieldType.Object && val.nested != null)
                {
                    ApplyValues(entity, rowInfo, fullName + '.', val.nested.ToArray(), isOriginal);
                }
                else
                {
                    ApplyValue(entity, rowInfo, fullName, fieldInfo, val, isOriginal);
                }
            });
        }

        private void ApplyValue(object entity, RowInfo rowInfo, string fullName, Field fieldInfo, ValueChange val,
            bool isOriginal)
        {
            var dataHelper = _services.DataHelper;
            if (isOriginal)
            {
                if ((val.flags & ValueFlags.Setted) == ValueFlags.Setted)
                    dataHelper.SetFieldValue(entity, fullName, fieldInfo, val.orig);
            }
            else
            {
                switch (rowInfo.changeType)
                {
                    case ChangeType.Deleted:
                    {
                        //For delete fill only original values
                        if ((val.flags & ValueFlags.Setted) == ValueFlags.Setted)
                            dataHelper.SetFieldValue(entity, fullName, fieldInfo, val.orig);
                    }
                        break;
                    case ChangeType.Added:
                    {
                        if (fieldInfo.isAutoGenerated)
                            return;
                        if ((val.flags & ValueFlags.Changed) == ValueFlags.Changed)
                        {
                            if (fieldInfo.isReadOnly && val.val != null && !fieldInfo.allowClientDefault)
                            {
                                throw new DomainServiceException(string.Format(ErrorStrings.ERR_PROPERTY_IS_READONLY,
                                    entity.GetType().Name, fieldInfo.fieldName));
                            }
                            if (fieldInfo.isAutoGenerated && val.val != null)
                            {
                                throw new DomainServiceException(string.Format(ErrorStrings.ERR_PROPERTY_IS_READONLY,
                                    entity.GetType().Name, fieldInfo.fieldName));
                            }
                            dataHelper.SetFieldValue(entity, fullName, fieldInfo, val.val);
                        }
                    }
                        break;
                    case ChangeType.Updated:
                    {
                        if ((val.flags & ValueFlags.Changed) == ValueFlags.Changed)
                        {
                            if (fieldInfo.isReadOnly || fieldInfo.isPrimaryKey > 0 ||
                                fieldInfo.fieldType == FieldType.RowTimeStamp || fieldInfo.isAutoGenerated)
                                throw new DomainServiceException(string.Format(ErrorStrings.ERR_PROPERTY_IS_READONLY,
                                    entity.GetType().Name, fieldInfo.fieldName));
                            if (!fieldInfo.isNullable && val.val == null)
                            {
                                throw new DomainServiceException(string.Format(ErrorStrings.ERR_FIELD_IS_NOT_NULLABLE,
                                    fieldInfo.fieldName));
                            }
                            dataHelper.SetFieldValue(entity, fullName, fieldInfo, val.val);
                        }
                        else if ((val.flags & ValueFlags.Setted) == ValueFlags.Setted)
                        {
                            if ((fieldInfo.isPrimaryKey > 0 || fieldInfo.fieldType == FieldType.RowTimeStamp ||
                                 fieldInfo.isNeedOriginal) && val.val != val.orig)
                            {
                                throw new DomainServiceException(string.Format(ErrorStrings.ERR_VAL_ORIGINAL_INVALID,
                                    fieldInfo.fieldName));
                            }
                            dataHelper.SetFieldValue(entity, fullName, fieldInfo, val.val);
                        }
                    }
                        break;
                }
            }
        }

        public void UpdateEntityFromRowInfo(object entity, RowInfo rowInfo, bool isOriginal)
        {
            var dbSetInfo = rowInfo.dbSetInfo;
            var values = rowInfo.values;
            ApplyValues(entity, rowInfo, "", rowInfo.values.ToArray(), isOriginal);
            var dataHelper = _services.DataHelper;

            if (!isOriginal && rowInfo.changeType == ChangeType.Added)
            {
                foreach (var pn in rowInfo.changeState.ParentRows)
                {
                    if (
                        !dataHelper.SetValue(entity, pn.association.childToParentName, pn.ParentRow.changeState.Entity,
                            false))
                    {
                        throw new DomainServiceException(string.Format(ErrorStrings.ERR_CAN_NOT_SET_PARENT_FIELD,
                            pn.association.childToParentName, rowInfo.dbSetInfo.EntityType.Name));
                    }
                }
            }
        }

        public void UpdateValuesFromEntity(object entity, string path, DbSetInfo dbSetInfo, ValueChange[] values)
        {
            var dataHelper = _services.DataHelper;
            Array.ForEach(values, val =>
            {
                var fullName = path + val.fieldName;
                var fieldInfo = dataHelper.getFieldInfo(dbSetInfo, fullName);
                if (!fieldInfo.GetIsIncludeInResult())
                    return;
                if (fieldInfo.fieldType == FieldType.Object && val.nested != null)
                {
                    UpdateValuesFromEntity(entity, fullName + '.', dbSetInfo, val.nested.ToArray());
                }
                else
                {
                    val.val = dataHelper.SerializeField(entity, fullName, fieldInfo);
                    val.flags = val.flags | ValueFlags.Refreshed;
                }
            });
        }

        public void CheckValuesChanges(RowInfo rowInfo, string path, ValueChange[] values)
        {
            var dbSetInfo = rowInfo.dbSetInfo;
            var dataHelper = _services.DataHelper;
            Array.ForEach(values, val =>
            {
                var fullName = path + val.fieldName;
                var fieldInfo = dataHelper.getFieldInfo(dbSetInfo, fullName);
                if (!fieldInfo.GetIsIncludeInResult())
                    return;
                if (fieldInfo.fieldType == FieldType.Object && val.nested != null)
                {
                    CheckValuesChanges(rowInfo, fullName + '.', val.nested.ToArray());
                }
                else
                {
                    string newVal;
                    if (isEntityValueChanged(rowInfo, fullName, fieldInfo, out newVal))
                    {
                        val.val = newVal;
                        val.flags = val.flags | ValueFlags.Refreshed;
                    }
                }
            });
        }

        public void UpdateRowInfoFromEntity(object entity, RowInfo rowInfo)
        {
            var dbSetInfo = rowInfo.dbSetInfo;
            UpdateValuesFromEntity(entity, "", dbSetInfo, rowInfo.values.ToArray());
            if (rowInfo.changeType == ChangeType.Added)
            {
                rowInfo.serverKey = rowInfo.GetRowKeyAsString();
            }
        }

        public bool isEntityValueChanged(RowInfo rowInfo, string fullName, Field fieldInfo, out string newVal)
        {
            var changeState = rowInfo.changeState;
            var dataHelper = _services.DataHelper;
            string oldVal = null;
            newVal = dataHelper.SerializeField(changeState.Entity, fullName, fieldInfo);
            if (changeState.OriginalEntity != null)
                oldVal = dataHelper.SerializeField(changeState.OriginalEntity, fullName, fieldInfo);
            return newVal != oldVal;
        }

        public void UpdateRowInfoAfterUpdates(RowInfo rowInfo)
        {
            CheckValuesChanges(rowInfo, "", rowInfo.values.ToArray());

            if (rowInfo.changeType == ChangeType.Added)
            {
                rowInfo.serverKey = rowInfo.GetRowKeyAsString();
            }
        }

        public object GetOriginalEntity(RowInfo rowInfo)
        {
            if (rowInfo == null)
            {
                throw new DomainServiceException(ErrorStrings.ERR_METH_APPLY_INVALID);
            }
            return rowInfo.changeState.OriginalEntity;
        }

        public T GetOriginalEntity<T>(RowInfo rowInfo)
            where T : class
        {
            return (T) GetOriginalEntity(rowInfo);
        }

        public object GetOriginalEntity(object entity, RowInfo rowInfo)
        {
            var dbEntity = Activator.CreateInstance(entity.GetType());
            UpdateEntityFromRowInfo(dbEntity, rowInfo, true);
            return dbEntity;
        }

        public object GetParentEntity(Type entityType, RowInfo rowInfo)
        {
            if (rowInfo == null)
            {
                throw new DomainServiceException(ErrorStrings.ERR_METH_APPLY_INVALID);
            }
            var parents = rowInfo.changeState.ParentRows;
            if (parents.Length == 0)
                return null;

            return
                parents.Where(p => p.ParentRow.dbSetInfo.EntityType == entityType)
                    .Select(p => p.ParentRow.changeState.Entity)
                    .FirstOrDefault();
        }

        public T GetParentEntity<T>(RowInfo rowInfo)
            where T : class
        {
            return (T) GetParentEntity(typeof(T), rowInfo);
        }


        public void InsertEntity(CachedMetadata metadata, RowInfo rowInfo)
        {
            var dbSetInfo = rowInfo.dbSetInfo;
            if (rowInfo.changeType != ChangeType.Added)
                throw new DomainServiceException(string.Format(ErrorStrings.ERR_REC_CHANGETYPE_INVALID,
                    dbSetInfo.EntityType.Name, rowInfo.changeType));
            var methodData = metadata.getOperationMethodInfo(dbSetInfo.dbSetName, MethodType.Insert);
            if (methodData == null)
                throw new DomainServiceException(string.Format(ErrorStrings.ERR_DB_INSERT_NOT_IMPLEMENTED,
                    dbSetInfo.EntityType.Name, GetType().Name));
            var dbEntity = Activator.CreateInstance(dbSetInfo.EntityType);
            UpdateEntityFromRowInfo(dbEntity, rowInfo, false);
            rowInfo.changeState.Entity = dbEntity;
            var instance = GetMethodOwner(methodData);
            methodData.methodInfo.Invoke(instance, new[] {dbEntity});
        }

        public void UpdateEntity(CachedMetadata metadata, RowInfo rowInfo)
        {
            var dbSetInfo = rowInfo.dbSetInfo;
            if (rowInfo.changeType != ChangeType.Updated)
                throw new DomainServiceException(string.Format(ErrorStrings.ERR_REC_CHANGETYPE_INVALID,
                    dbSetInfo.EntityType.Name, rowInfo.changeType));
            var methodData = metadata.getOperationMethodInfo(dbSetInfo.dbSetName, MethodType.Update);
            if (methodData == null)
                throw new DomainServiceException(string.Format(ErrorStrings.ERR_DB_UPDATE_NOT_IMPLEMENTED,
                    dbSetInfo.EntityType.Name, GetType().Name));
            var dbEntity = Activator.CreateInstance(dbSetInfo.EntityType);
            UpdateEntityFromRowInfo(dbEntity, rowInfo, false);
            var original = GetOriginalEntity(dbEntity, rowInfo);
            rowInfo.changeState.Entity = dbEntity;
            rowInfo.changeState.OriginalEntity = original;
            var instance = GetMethodOwner(methodData);
            //apply this changes to entity that is in the database (this is done in user domain service method)
            methodData.methodInfo.Invoke(instance, new[] {dbEntity});
        }

        public void DeleteEntity(CachedMetadata metadata, RowInfo rowInfo)
        {
            var dbSetInfo = rowInfo.dbSetInfo;
            if (rowInfo.changeType != ChangeType.Deleted)
                throw new DomainServiceException(string.Format(ErrorStrings.ERR_REC_CHANGETYPE_INVALID,
                    dbSetInfo.EntityType.Name, rowInfo.changeType));

            var methodData = metadata.getOperationMethodInfo(dbSetInfo.dbSetName, MethodType.Delete);
            if (methodData == null)
                throw new DomainServiceException(string.Format(ErrorStrings.ERR_DB_DELETE_NOT_IMPLEMENTED,
                    dbSetInfo.EntityType.Name, GetType().Name));

            var dbEntity = Activator.CreateInstance(dbSetInfo.EntityType);
            UpdateEntityFromRowInfo(dbEntity, rowInfo, true);
            rowInfo.changeState.Entity = dbEntity;
            rowInfo.changeState.OriginalEntity = dbEntity;
            var instance = GetMethodOwner(methodData);
            methodData.methodInfo.Invoke(instance, new[] {dbEntity});
        }

        public async Task<bool> ValidateEntity(CachedMetadata metadata, RequestContext requestContext)
        {
            var validatorsContainer = metadata.ValidatorsContainer;
            var rowInfo = requestContext.CurrentRowInfo;
            var dbSetInfo = rowInfo.dbSetInfo;
            IEnumerable<ValidationErrorInfo> errs1 = null;
            IEnumerable<ValidationErrorInfo> errs2 = null;
            var mustBeChecked = new LinkedList<string>();
            LinkedList<string> skipCheckList = null;
            var dataHelper = _services.DataHelper;
            var validationHelper = _services.ValidationHelper;

            if (rowInfo.changeType == ChangeType.Added)
            {
                skipCheckList = new LinkedList<string>();
                foreach (var pn in rowInfo.changeState.ParentRows)
                {
                    foreach (var frel in pn.association.fieldRels)
                    {
                        skipCheckList.AddLast(frel.childField);
                    }
                }
            }

            foreach (var fieldInfo in dbSetInfo.fieldInfos)
            {
                dataHelper.ForEachFieldInfo("", fieldInfo, (fullName, f) =>
                {
                    if (!f.GetIsIncludeInResult())
                        return;
                    if (f.fieldType == FieldType.Object || f.fieldType == FieldType.ServerCalculated)
                        return;

                    var value = dataHelper.SerializeField(rowInfo.changeState.Entity, fullName, f);
                    if (rowInfo.changeType == ChangeType.Added)
                    {
                        var isSkip = f.isAutoGenerated ||
                                     (skipCheckList != null && skipCheckList.Any(n => n == fullName));
                        if (!isSkip)
                        {
                            validationHelper.CheckValue(f, value);
                            mustBeChecked.AddLast(fullName);
                        }
                    }
                    else if (rowInfo.changeType == ChangeType.Updated)
                    {
                        string newVal;
                        var isChanged = isEntityValueChanged(rowInfo, fullName, f, out newVal);
                        if (isChanged)
                        {
                            validationHelper.CheckValue(f, newVal);
                        }
                        if (isChanged)
                            mustBeChecked.AddLast(fullName);
                    }
                });
            }

            rowInfo.changeState.NamesOfChangedFields = mustBeChecked.ToArray();
            var methodData = metadata.getOperationMethodInfo(dbSetInfo.dbSetName, MethodType.Validate);
            if (methodData != null)
            {
                var instance = GetMethodOwner(methodData);
                var invokeRes = methodData.methodInfo.Invoke(instance,
                    new[] {rowInfo.changeState.Entity, rowInfo.changeState.NamesOfChangedFields});
                errs1 = (IEnumerable<ValidationErrorInfo>) await GetMethodResult(invokeRes).ConfigureAwait(false);
            }

            if (errs1 == null)
                errs1 = Enumerable.Empty<ValidationErrorInfo>();

            var validator = validatorsContainer.GetValidator(requestContext, rowInfo.dbSetInfo.EntityType);
            if (validator != null)
            {
                errs2 =
                    await
                        validator.ValidateModelAsync(rowInfo.changeState.Entity,
                            rowInfo.changeState.NamesOfChangedFields);
            }

            if (errs2 == null)
                errs2 = Enumerable.Empty<ValidationErrorInfo>();

            errs1 = errs1.Concat(errs2);

            if (errs1 != null && errs1.Count() > 0)
            {
                rowInfo.changeState.ValidationErrors = errs1.ToArray();
                return false;
            }

            return true;
        }

        public static async Task<object> GetMethodResult(object invokeRes)
        {
            var typeInfo = invokeRes != null ? invokeRes.GetType() : null;
            if (typeInfo != null && invokeRes is Task)
            {
                await ((Task) invokeRes).ConfigureAwait(false);
                return typeInfo.GetProperty("Result").GetValue(invokeRes, null);
            }
            return invokeRes;
        }
    }
}